language: python

python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
 - "nightly"
 - "pypy"
 - "pypy3"

matrix:
  allow_failures:
    - python: nightly
    - python: "pypy"
    - python: "pypy3"

sudo: false

addons:
  apt:
    packages:
      # gfortran is needed to build the examples
      - gfortran

env:
  matrix:
    - USE_PIP=ON
    - USE_PIP=OFF

script:
  # install latest release from pip
  # .. or install from source
  #
  # note: since this is executed in a virtualenv
  #       we can not add "--user"
  - if [ "$USE_PIP" == "ON" ]; then
      pip install Forthon;
    else
      python setup.py install;
    fi
  # Python3 test
  - FORTHON_FOUND=$(which Forthon >/dev/null && { echo 0; } || { echo 1; })
  - if [ $FORTHON_FOUND -eq 0 ]; then
      export FORTHON_CMD=Forthon;
    else
      echo "Python 3 - overwriting Forthon executable with Forthon3";
      export FORTHON_CMD=Forthon3;
    fi
  - which $FORTHON_CMD
  # now build some examples
  - cd example
  - make FORTHON=$FORTHON_CMD
  # broken legacy example:
  # - cd ../example2
  # - make FORTHON=$FORTHON_CMD
  - cd ../simpleexample
  - make FORTHON=$FORTHON_CMD
  - cd ..
