language: python

python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
 - "nightly"
 - "pypy"
 - "pypy3"

matrix:
  allow_failures:
    - python: nightly
    - python: "pypy"
    - python: "pypy3"

sudo: false

env:
  matrix:
    - USE_PIP=ON
    - USE_PIP=OFF

script:
  # install latest release from pip
  # .. or install from source
  #
  # note: since this is executed in a virtualenv
  #       we can not add "--user"
  - if [ "$USE_PIP" == "ON" ]; then
      pip install Forthon;
    else
      python setup.py install;
    fi
